# Creating DataFrames

Many ways to do it!

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[1.33241346e-01 6.17142137e-01 8.87672975e-01]
 [3.61103059e-01 1.60214789e-01 8.21561076e-01]
 [9.92619209e-01 6.68686213e-01 5.18484119e-01]
 [3.40782050e-05 7.40083058e-01 2.62629137e-01]
 [2.46588712e-01 1.02937381e-01 3.86685208e-01]]


A         B         C
0  0.133241  0.617142  0.887673
1  0.361103  0.160215  0.821561
2  0.992619  0.668686  0.518484
3  0.000034  0.740083  0.262629
4  0.246589  0.102937  0.386685

In [5]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [8]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", int), ("B", (str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [9]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John